# Global environment variables for builds.
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org|direct
  - REPO=github.com/coolguy1771/rssc

# Hooks to run before any build is run.
before:
  hooks:
    - go version | grep --quiet "go1\.25\.3" || echo "Go binary version must be 1.25.3"
    - go mod download

# Binary builds.
builds:
  - id: scaleset-controller
    main: ./cmd
    binary: scaleset-controller
    mod_timestamp: "{{ .CommitTimestamp }}"
    asmflags:
      - all=-trimpath={{ .Env.PWD }}
    gcflags:
      - all=-trimpath={{ .Env.PWD }}
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64

# Use most recent tag and short commit for snapshot version.
snapshot:
  name_template: "{{ .Env.GIT_VERSION }}"

# Binary-only archives (no tarballs).
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: "checksums.txt"
