apiVersion: scaleset.actions.github.com/v1alpha1
kind: AutoscaleSet
metadata:
  name: my-autoscaleset
  namespace: default
  labels:
    app.kubernetes.io/name: scaleset-controller
    app.kubernetes.io/managed-by: manual
    environment: test
spec:
  githubConfigURL: https://github.com/coolguy1771/home-ops
  scaleSetName: github-scale-set
  runnerImage: ghcr.io/actions/actions-runner:2.331.0
  runnerGroup: default
  minRunners: 1
  maxRunners: 10
  labels:
    - type: System
      name: linux
    - type: User
      name: kubernetes
    - type: User
      name: test
  runnerTemplate:
    metadata:
      labels:
        environment: test
        team: platform
        app: github-runner
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "runner"
          effect: "NoSchedule"
      env:
        - name: RUNNER_EXTRA_LABELS
          value: "kubernetes,self-hosted,test"
  githubApp:
    clientID: "165833"
    installationID: 22426815
    privateKeySecretRef:
      name: github-app-secret
      namespace: default
