/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AutoscaleSetSpec defines the desired state of AutoscaleSet
type AutoscaleSetSpec struct {
	// GitHubConfigURL is the URL for the GitHub org/repo/enterprise
	// Example: https://github.com/org/repo
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^https://.*`
	GitHubConfigURL string `json:"githubConfigURL"`

	// ScaleSetName is the name of the scale set
	// This must be unique within the runner group
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	ScaleSetName string `json:"scaleSetName"`

	// RunnerGroup is the runner group name (default: "default")
	// +kubebuilder:default="default"
	RunnerGroup string `json:"runnerGroup,omitempty"`

	// Labels are custom labels for the scale set
	Labels []ScaleSetLabel `json:"labels,omitempty"`

	// MinRunners is the minimum number of runners to maintain
	// +kubebuilder:validation:Minimum=0
	// +kubebuilder:default=0
	MinRunners *int32 `json:"minRunners,omitempty"`

	// MaxRunners is the maximum number of runners
	// +kubebuilder:validation:Minimum=1
	// +kubebuilder:default=10
	MaxRunners *int32 `json:"maxRunners,omitempty"`

	// RunnerImage is the container image for runners
	// +kubebuilder:validation:Required
	RunnerImage string `json:"runnerImage"`

	// GitHubApp is GitHub App authentication
	GitHubApp *GitHubAppAuth `json:"githubApp,omitempty"`

	// PersonalAccessToken is PAT authentication (alternative to GitHub App)
	PersonalAccessToken *PersonalAccessTokenAuth `json:"personalAccessToken,omitempty"`

	// RunnerTemplate is the pod template for creating runners
	RunnerTemplate *RunnerPodTemplate `json:"runnerTemplate,omitempty"`
}

// ScaleSetLabel represents a label for the scale set
type ScaleSetLabel struct {
	// Type is the label type (default: "System")
	Type string `json:"type,omitempty"`

	// Name is the label name
	Name string `json:"name"`
}

// GitHubAppAuth defines GitHub App authentication
type GitHubAppAuth struct {
	// ClientID is the GitHub App Client ID
	// +kubebuilder:validation:Required
	ClientID string `json:"clientID"`

	// InstallationID is the GitHub App Installation ID
	// +kubebuilder:validation:Required
	InstallationID int64 `json:"installationID"`

	// PrivateKeySecretRef is a reference to a secret containing the private key
	// The secret must contain a key named "privateKey" with the PEM-encoded private key
	// +kubebuilder:validation:Required
	PrivateKeySecretRef SecretRef `json:"privateKeySecretRef"`
}

// PersonalAccessTokenAuth defines PAT authentication
type PersonalAccessTokenAuth struct {
	// TokenSecretRef is a reference to a secret containing the PAT
	// The secret must contain a key named "token" with the personal access token
	// +kubebuilder:validation:Required
	TokenSecretRef SecretRef `json:"tokenSecretRef"`
}

// SecretRef references a Kubernetes Secret
type SecretRef struct {
	// Name is the name of the secret
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Namespace is the namespace of the secret (defaults to AutoscaleSet namespace)
	Namespace string `json:"namespace,omitempty"`

	// Key is the key in the secret (defaults to "privateKey" for GitHubApp, "token" for PAT)
	Key string `json:"key,omitempty"`
}

// RunnerPodTemplateMetadata contains only the metadata fields needed for pod templates
type RunnerPodTemplateMetadata struct {
	// Labels are labels to apply to the pod
	Labels map[string]string `json:"labels,omitempty"`

	// Annotations are annotations to apply to the pod
	Annotations map[string]string `json:"annotations,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerPodTemplateMetadata) DeepCopyInto(out *RunnerPodTemplateMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerPodTemplateMetadata.
func (in *RunnerPodTemplateMetadata) DeepCopy() *RunnerPodTemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(RunnerPodTemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// RunnerPodTemplate defines the pod template for runners
type RunnerPodTemplate struct {
	// Metadata contains labels and annotations for the pod
	Metadata RunnerPodTemplateMetadata `json:"metadata,omitempty"`

	// Spec is the pod spec
	Spec RunnerPodSpec `json:"spec,omitempty"`
}

// RunnerPodSpec defines the pod spec for runners
type RunnerPodSpec struct {
	// NodeSelector is a selector which must be true for the pod to fit on a node
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`

	// Tolerations allow the pod to be scheduled on nodes with matching taints
	// This is a simplified version - in practice, you might want to use corev1.Toleration
	Tolerations []Toleration `json:"tolerations,omitempty"`

	// Resources are the resource requirements for the runner pod
	// This is a simplified version - in practice, you might want to use corev1.ResourceRequirements
	Resources ResourceRequirements `json:"resources,omitempty"`

	// Env are additional environment variables for the runner pod
	// This is a simplified version - in practice, you might want to use corev1.EnvVar
	Env []EnvVar `json:"env,omitempty"`
}

// Toleration represents a Kubernetes toleration
// This is a simplified version - in practice, you might want to use corev1.Toleration
type Toleration struct {
	Key      string `json:"key,omitempty"`
	Operator string `json:"operator,omitempty"`
	Value    string `json:"value,omitempty"`
	Effect   string `json:"effect,omitempty"`
}

// ResourceRequirements represents Kubernetes resource requirements
// This is a simplified version - in practice, you might want to use corev1.ResourceRequirements
type ResourceRequirements struct {
	Limits   map[string]string `json:"limits,omitempty"`
	Requests map[string]string `json:"requests,omitempty"`
}

// EnvVar represents an environment variable
// This is a simplified version - in practice, you might want to use corev1.EnvVar
type EnvVar struct {
	Name  string `json:"name"`
	Value string `json:"value,omitempty"`
}

// AutoscaleSetStatus defines the observed state of AutoscaleSet
type AutoscaleSetStatus struct {
	// ScaleSetID is the GitHub scale set ID
	ScaleSetID *int `json:"scaleSetID,omitempty"`

	// Phase is the current phase (Pending, Active, Error)
	Phase string `json:"phase,omitempty"`

	// Conditions represent the latest available observations
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// CurrentRunners is the current number of runners
	CurrentRunners int32 `json:"currentRunners,omitempty"`

	// DesiredRunners is the desired number of runners
	DesiredRunners int32 `json:"desiredRunners,omitempty"`

	// LastMessageID is the last processed message ID
	LastMessageID int `json:"lastMessageID,omitempty"`

	// Labels are the current labels on the scale set in GitHub
	Labels []ScaleSetLabel `json:"labels,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:resource:categories=github;scaleset,shortName=asss
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase",description="Current phase (Pending, Active, Error)"
// +kubebuilder:printcolumn:name="ScaleSetID",type="integer",JSONPath=".status.scaleSetID",description="GitHub scale set ID"
// +kubebuilder:printcolumn:name="Current",type="integer",JSONPath=".status.currentRunners",description="Current number of runners"
// +kubebuilder:printcolumn:name="Desired",type="integer",JSONPath=".status.desiredRunners",description="Desired/queued job count"
// +kubebuilder:printcolumn:name="Labels",type="string",JSONPath=".status.labels[*].name",priority=1,description="Scale set labels"
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:selectablefield:JSONPath=".status.phase"

// AutoscaleSet is the Schema for the autoscalesets API
type AutoscaleSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AutoscaleSetSpec   `json:"spec,omitempty"`
	Status            AutoscaleSetStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AutoscaleSetList contains a list of AutoscaleSet
type AutoscaleSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AutoscaleSet `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AutoscaleSet{}, &AutoscaleSetList{})
}
